
name: flutter_wm_ble_com
description: Wirepas Firmware-Update Demo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  flex_color_scheme: ^6.1.2
  permission_handler: ^10.2.0
  freezed_annotation: ^2.2.0
  statemachine: ^3.3.1
  flutter_ble_peripheral:
    path: "./flutter_ble_peripheral"
  flutter_reactive_ble:
    path: "./flutter_reactive_ble/packages/flutter_reactive_ble"
  synchronized: ^3.0.1
  wakelock: ^0.6.2
  percent_indicator: ^4.2.3
  flutter_hooks: ^0.18.6
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.1.4
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/firmware/

flutter_icons:
  android: launcher_icon
  remove_alpha_ios: true
  ios: true
  image_path: assets/icons/launcher.png

