import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'message.freezed.dart';

enum MessageState {
  queueMessage,
  sendingMessage,
  timeoutMessage,
  hasMore,
  done,
}

@freezed
class Message with _$Message {
  const factory Message({
    required Uint8List buffer,
    required int messageId,
    required MessageState state,
    required int timeoutMs,
    required String commandName,
  }) = _Message;
}
